import sys

"""
Python скрипт для аннотации варианта без использования каких-либо сторонних ПО.

Есть 4 критические позиции для каждого гена, после которых стоп кодоны и фреймшифты считаем патогенными -
уже в формате диапазонов (.tsv файл: ген, первая координата, вторая координата, патогенный диапазон или нет - соответственно по два диапазона на ген)

Алгоритм работы:
Извлекаем базы варианта и рядом с вариантом в референсных и альтернативных последовательностях
Если в какой-то из них фреймшифт или стоп-кодон - помечаем
Смотрим последние фреймшифты (после критических позиций) и стоп кодоны в диапазоне, их считаем норм, остальные нет.

"""


def reverse_complement(orig_sequence):
    complement_lr = list(orig_sequence.upper())
    for i in range(len(complement_lr)):
        if complement_lr[i] == 'A':
            complement_lr[i] = 'T'
        elif complement_lr[i] == 'G':
            complement_lr[i] = 'C'
        elif complement_lr[i] == 'T':
            complement_lr[i] = 'A'
        elif complement_lr[i] == 'C':
            complement_lr[i] = 'G'
    complement_lr = ''.join(complement_lr)
    complement_rl = complement_lr[::-1]

    # print('orig_sequence', orig_sequence)
    # print('complement_lr', complement_lr)
    # print('complement_rl', complement_rl)

    return complement_rl


def input_dialog():
    if len(sys.argv) == 1:
        variant_name = input('Input the variant: ')
        variant_b = ''.join(char for char in variant_name.split(':')[-1] if not char.isnumeric())
        while len(variant_name.split(':')) == 1 or len(variant_name.split('>')) == 1 \
                or not all([b.upper() in 'ACGT>' for b in variant_b]):
            variant_name = input(
                'Input the variant chromosome, position and alleles in the correct format [CHR:POSref>alt]: ')
            variant_b = ''.join(char for char in variant_name.split(':')[-1] if not char.isnumeric())

    else:
        variant_name = sys.argv[1]
        variant_b = ''.join(char for char in variant_name.split(':')[-1] if not char.isnumeric())
        while len(variant_name.split(':')) == 1 or len(variant_name.split('>')) == 1 \
                or not all([b.upper() in 'ACGT>' for b in variant_b]):
            variant_name = input(
                'Input the variant chromosome, position and alleles in the correct format [CHR:POSref>alt]: ')
            variant_b = ''.join(char for char in variant_name.split(':')[-1] if not char.isnumeric())

    return variant_name


if __name__ == '__main__':
    print('USAGE:', 'python consequence_classification_standalone.py [variant as CHR:POSref>alt]')

    # reference truncated to the ABC region
    ref_dict = {
        'chr11': [
            [108098352,
             108098423,
             'ATGAGTCTAGTACTTAATGATCTGCTTATCTGCTGCCGTCAACTAGAACATGATAGAGCTACAGAACGAAAG'],
            [108098503,
             108098615,
             'AAAGAAGTTGAGAAATTTAAGCGCCTGATTCGAGATCCTGAAACAATTAAACATCTAGATCGGCATTCAGATTCCAAACAAGGAAAATATTTGAATTGGGATGCTGTTTTTAG'],
            [108099905,
             108100050,
             'ATTTTTACAGAAATATATTCAGAAAGAAACAGAATGTCTGAGAATAGCAAAACCAAATGTATCAGCCTCAACACAAGCCTCCAGGCAGAAAAAGATGCAGGAAATCAGTAGTTTGGTCAAATACTTCATCAAATGTGCAAACAGAA'],
            [108106397,
             108106561,
             'GAGCACCTAGGCTAAAATGTCAAGAACTCTTAAATTATATCATGGATACAGTGAAAGATTCATCTAATGGTGCTATTTACGGAGCTGATTGTAGCAACATACTACTCAAAGACATTCTTTCTGTGAGAAAATACTGGTGTGAAATATCTCAGCAACAGTGGTTAG'],
            [108114680,
             108114845,
             'AATTGTTCTCTGTGTACTTCAGGCTCTATCTGAAACCTTCACAAGATGTTCATAGAGTTTTAGTGGCTAGAATAATTCATGCTGTTACCAAAGGATGCTGTTCTCAGACTGACGGATTAAATTCCAAATTTTTGGACTTTTTTTCCAAGGCTATTCAGTGTGCGAG'],
            [108115515,
             108115753,
             'ACAAGAAAAGAGCTCTTCAGGTCTAAATCATATCTTAGCAGCTCTTACTATCTTCCTCAAGACTTTGGCTGTCAACTTTCGAATTCGAGTGTGTGAATTAGGAGATGAAATTCTTCCCACTTTGCTTTATATTTGGACTCAACATAGGCTTAATGATTCTTTAAAAGAAGTCATTATTGAATTATTTCAACTGCAAATTTATATCCATCATCCGAAAGGAGCCAAAACCCAAGAAAAAG'],
            [108117691,
             108117854,
             'GTGCTTATGAATCAACAAAATGGAGAAGTATTTTATACAACTTATATGATCTGCTAGTGAATGAGATAAGTCATATAGGAAGTAGAGGAAAGTATTCTTCAGGATTTCGTAATATTGCCGTCAAAGAAAATTTGATTGAATTGATGGCAGATATCTGTCACCAG'],
            [108119660,
             108119829,
             'GTTTTTAATGAAGATACCAGATCCTTGGAGATTTCTCAATCTTACACTACTACACAAAGAGAATCTAGTGATTACAGTGTCCCTTGCAAAAGGAAGAAAATAGAACTAGGCTGGGAAGTAATAAAAGATCACCTTCAGAAGTCACAGAATGATTTTGATCTTGTGCCTTG'],
            [108121428,
             108121799,
             'GCTACAGATTGCAACCCAATTAATATCAAAGTATCCTGCAAGTTTACCTAACTGTGAGCTGTCTCCATTACTGATGATACTATCTCAGCTTCTACCCCAACAGCGACATGGGGAACGTACACCATATGTGTTACGATGCCTTACGGAAGTTGCATTGTGTCAAGACAAGAGGTCAAACCTAGAAAGCTCACAAAAGTCAGATTTATTAAAACTCTGGAATAAAATTTGGTGTATTACCTTTCGTGGTATAAGTTCTGAGCAAATACAAGCTGAAAACTTTGGCTTACTTGGAGCCATAATTCAGGGTAGTTTAGTTGAGGTTGACAGAGAATTCTGGAAGTTATTTACTGGGTCAGCCTGCAGACCTTCATG'],
            [108122564,
             108122758,
             'TCCTGCAGTATGCTGTTTGACTTTGGCACTGACCACCAGTATAGTTCCAGGAACGGTAAAAATGGGAATAGAGCAAAATATGTGTGAAGTAAATAGAAGCTTTTCTTTAAAGGAATCAATAATGAAATGGCTCTTATTCTATCAGTTAGAGGGTGACTTAGAAAATAGCACAGAAGTGCCTCCAATTCTTCACAG'],
            [108123544,
             108123639,
             'TAATTTTCCTCATCTTGTACTGGAGAAAATTCTTGTGAGTCTCACTATGAAAAACTGTAAAGCTGCAATGAATTTTTTCCAAAGCGTGCCAGAATG'],
            [108124541,
             108124766,
             'TGAACACCACCAAAAAGATAAAGAAGAACTTTCATTCTCAGAAGTAGAAGAACTATTTCTTCAGACAACTTTTGACAAGATGGACTTTTTAACCATTGTGAGAGAATGTGGTATAGAAAAGCACCAGTCCAGTATTGGCTTCTCTGTCCACCAGAATCTCAAGGAATCACTGGATCGCTGTCTTCTGGGATTATCAGAACAGCTTCTGAATAATTACTCATCTGAG'],
            [108126942,
             108127067,
             'ATTACAAATTCAGAAACTCTTGTCCGGTGTTCACGTCTTTTGGTGGGTGTCCTTGGCTGCTACTGTTACATGGGTGTAATAGCTGAAGAGGAAGCATATAAGTCAGAATTATTCCAGAAAGCCAAG'],
            [108128208,
             108128333,
             'TCTCTAATGCAATGTGCAGGAGAAAGTATCACTCTGTTTAAAAATAAGACAAATGAGGAATTCAGAATTGGTTCCTTGAGAAATATGATGCAGCTATGTACACGTTGCTTGAGCAACTGTACCAAG'],
            [108129713,
             108129802,
             'AAGAGTCCAAATAAGATTGCATCTGGCTTTTTCCTGCGATTGTTAACATCAAAGCTAATGAATGACATTGCAGATATTTGTAAAAGTTTA'],
            [108137898,
             108138069,
             'GCATCCTTCATCAAAAAGCCATTTGACCGTGGAGAAGTAGAATCAATGGAAGATGATACTAATGGAAATCTAATGGAGGTGGAGGATCAGTCATCCATGAATCTATTTAACGATTACCCTGATAGTAGTGTTAGTGATGCAAACGAACCTGGAGAGAGCCAAAGTACCATAG'],
            [108139137,
             108139336,
             'GTGCCATTAATCCTTTAGCTGAAGAATATCTGTCAAAGCAAGATCTACTTTTCTTAGACATGCTCAAGTTCTTGTGTTTGTGTGTAACTACTGCTCAGACCAATACTGTGTCCTTTAGGGCAGCTGATATTCGGAGGAAATTGTTAATGTTAATTGATTCTAGCACGCTAGAACCTACCAAATCCCTCCACCTGCATATG'],
            [108141791,
             108141873,
             'TATCTAATGCTTTTAAAGGAGCTTCCTGGAGAAGAGTACCCCTTGCCAATGGAAGATGTTCTTGAACTTCTGAAACCACTATC'],
            [108141978,
             108142133,
             'CAATGTGTGTTCTTTGTATCGTCGTGACCAAGATGTTTGTAAAACTATTTTAAACCATGTCCTTCATGTAGTGAAAAACCTAGGTCAAAGCAATATGGACTCTGAGAACACAAGGGATGCTCAAGGACAGTTTCTTACAGTAATTGGAGCATTTTG'],
            [108143259,
             108143334,
             'GCATCTAACAAAGGAGAGGAAATATATATTCTCTGTAAGAATGGCCCTAGTAAATTGCCTTAAAACTTTGCTTGAG'],
            [108143449,
             108143579,
             'GCTGATCCTTATTCAAAATGGGCCATTCTTAATGTAATGGGAAAAGACTTTCCTGTAAATGAAGTATTTACACAATTTCTTGCTGACAATCATCACCAAGTTCGCATGTTGGCTGCAGAGTCAATCAATAG'],
            [108150218,
             108150335,
             'ATTGTTCCAGGACACGAAGGGAGATTCTTCCAGGTTACTGAAAGCACTTCCTTTGAAGCTTCAGCAAACAGCTTTTGAAAATGCATACTTGAAAGCTCAGGAAGGAATGAGAGAAATG'],
            [108151722,
             108151895,
             'TCCCATAGTGCTGAGAACCCTGAAACTTTGGATGAAATTTATAATAGAAAATCTGTTTTACTGACGTTGATAGCTGTGGTTTTATCCTGTAGCCCTATCTGCGAAAAACAGGCTTTGTTTGCCCTGTGTAAATCTGTGAAAGAGAATGGATTAGAACCTCACCTTGTGAAAAAG'],
            [108153437,
             108153606,
             'GTTTTAGAGAAAGTTTCTGAAACTTTTGGATATAGACGTTTAGAAGACTTTATGGCATCTCATTTAGATTATCTGGTTTTGGAATGGCTAAATCTTCAAGATACTGAATACAACTTATCTTCTTTTCCTTTTATTTTATTAAACTACACAAATATTGAGGATTTCTATAG'],
            [108154954,
             108155200,
             'ATCTTGTTATAAGGTTTTGATTCCACATCTGGTGATTAGAAGTCATTTTGATGAGGTGAAGTCCATTGCTAATCAGATTCAAGAGGACTGGAAAAGTCTTCTAACAGACTGCTTTCCAAAGATTCTTGTAAATATTCTTCCTTATTTTGCCTATGAGGGTACCAGAGACAGTGGGATGGCACAGCAAAGAGAGACTGCTACCAAGGTCTATGATATGCTTAAAAGTGAAAACTTATTGGGAAAACAG'],
            [108158327,
             108158442,
             'ATTGATCACTTATTCATTAGTAATTTACCAGAGATTGTGGTGGAGTTATTGATGACGTTACATGAGCCAGCAAATTCTAGTGCCAGTCAGAGCACTGACCTCTGTGACTTTTCAGG'],
            [108159704,
             108159830,
             'GGATTTGGATCCTGCTCCTAATCCACCTCATTTTCCATCGCATGTGATTAAAGCAACATTTGCCTATATCAGCAATTGTCATAAAACCAAGTTAAAAAGCATTTTAGAAATTCTTTCCAAAAGCCCT'],
            [108160329,
             108160528,
             'GATTCCTATCAGAAAATTCTTCTTGCCATATGTGAGCAAGCAGCTGAAACAAATAATGTTTATAAGAAGCACAGAATTCTTAAAATATATCACCTGTTTGTTAGTTTATTACTGAAAGATATAAAAAGTGGCTTAGGAGGAGCTTGGGCCTTTGTTCTTCGAGACGTTATTTATACTTTGATTCACTATATCAACCAAAG'],
            [108163346,
             108163520,
             'GCCTTCTTGTATCATGGATGTGTCATTACGTAGCTTCTCCCTTTGTTGTGACTTATTAAGTCAGGTTTGCCAGACAGCCGTGACTTACTGTAAGGATGCTCTAGAAAACCATCTTCATGTTATTGTTGGTACACTTATACCCCTTGTGTATGAGCAGGTGGAGGTTCAGAAACAG'],
            [108164040,
             108164204,
             'GTATTGGACTTGTTGAAATACTTAGTGATAGATAACAAGGATAATGAAAACCTCTATATCACGATTAAGCTTTTAGATCCTTTTCCTGACCATGTTGTTTTTAAGGATTTGCGTATTACTCAGCAAAAAATCAAATACAGTAGAGGACCCTTTTCACTCTTGGAG'],
            [108165654,
             108165786,
             'GAAATTAACCATTTTCTCTCAGTAAGTGTTTATGATGCACTTCCATTGACAAGACTTGAAGGACTAAAGGATCTTCGAAGACAACTGGAACTACATAAAGATCAGATGGTGGACATTATGAGAGCTTCTCAGG'],
            [108168014,
             108168109,
             'ATAATCCGCAAGATGGGATTATGGTGAAACTAGTTGTCAATTTGTTGCAGTTATCCAAGATGGCAATAAACCACACTGGTGAAAAAGAAGTTCTAG'],
            [108170441,
             108170612,
             'AGGCTGTTGGAAGCTGCTTGGGAGAAGTGGGTCCTATAGATTTCTCTACCATAGCTATACAACATAGTAAAGATGCATCTTATACCAAGGCCCTTAAGTTATTTGAAGATAAAGAACTTCAGTGGACCTTCATAATGCTGACCTACCTGAATAACACACTGGTAGAAGATTG'],
            [108172375,
             108172516,
             'TGTCAAAGTTCGATCAGCAGCTGTTACCTGTTTGAAAAACATTTTAGCCACAAAGACTGGACATAGTTTCTGGGAGATTTATAAGATGACAACAGATCCAATGCTGGCCTATCTACAGCCTTTTAGAACATCAAGAAAAAAG'],
            [108173580,
             108173756,
             'TTTTTAGAAGTACCCAGATTTGACAAAGAAAACCCTTTTGAAGGCCTGGATGATATAAATCTGTGGATTCCTCTAAGTGAAAATCATGACATTTGGATAAAGACACTGACTTGTGCTTTTTTGGACAGTGGAGGCACAAAATGTGAAATTCTTCAATTATTAAAGCCAATGTGTGAA'],
            [108175402,
             108175579,
             'GTGAAAACTGACTTTTGTCAGACTGTACTTCCATACTTGATTCATGATATTTTACTCCAAGATACAAATGAATCATGGAGAAATCTGCTTTCTACACATGTTCAGGGATTTTTCACCAGCTGTCTTCGACACTTCTCGCAAACGAGCCGATCCACAACCCCTGCAAACTTGGATTCAG'],
            [108178624,
             108178711,
             'AGTCAGAGCACTTTTTCCGATGCTGTTTGGATAAAAAATCACAAAGAACAATGCTTGCTGTTGTGGACTACATGAGAAGACAAAAGAG'],
            [108180887,
             108181042,
             'ACCTTCTTCAGGAACAATTTTTAATGATGCTTTCTGGCTGGATTTAAATTATCTAGAAGTTGCCAAGGTAGCTCAGTCTTGTGCTGCTCACTTTACAGCTTTACTCTATGCAGAAATCTATGCAGATAAGAAAAGTATGGATGATCAAGAGAAAAG'],
            [108183138,
             108183225,
             'AAGTCTTGCATTTGAAGAAGGAAGCCAGAATACAACTATTTCTAGCTTGAGTGAAAAAAGTAAAGAAGAAACTGGAATAAGTTTACAG'],
            [108186550,
             108186638,
             'GATCTTCTCTTAGAAATCTACAGAAGTATAGGGGAGCCAGATAGTTTGTATGGCTGTGGTGGAGGGAAGATGTTACAACCCATTACTAG'],
            [108186738,
             108186840,
             'ACTACGAACATATGAACACGAAGCAATGTGGGGCAAAGCCCTAGTAACATATGACCTCGAAACAGCAATCCCCTCATCAACACGCCAGGCAGGAATCATTCAG'],
            [108188100,
             108188248,
             'GCCTTGCAGAATTTGGGACTCTGCCATATTCTTTCCGTCTATTTAAAAGGATTGGATTATGAAAATAAAGACTGGTGTCCTGAACTAGAAGAACTTCATTACCAAGCAGCATGGAGGAATATGCAGTGGGACCATTGCACTTCCGTCAG'],
            [108190681,
             108190785,
             'CAAAGAAGTAGAAGGAACCAGTTACCATGAATCATTGTACAATGCTCTACAATCTCTAAGAGACAGAGAATTCTCTACATTTTATGAAAGTCTCAAATATGCCAG'],
            [108192028,
             108192147,
             'AGTAAAAGAAGTGGAAGAGATGTGTAAGCGCAGCCTTGAGTCTGTGTATTCGCTCTATCCCACACTTAGCAGGTTGCAGGCCATTGGAGAGCTGGAAAGCATTGGGGAGCTTTTCTCAAG'],
            [108196037,
             108196271,
             'ATCAGTCACACATAGACAACTCTCTGAAGTATATATTAAGTGGCAGAAACACTCCCAGCTTCTCAAGGACAGTGATTTTAGTTTTCAGGAGCCTATCATGGCTCTACGCACAGTCATTTTGGAGATCCTGATGGAAAAGGAAATGGACAACTCACAAAGAGAATGTATTAAGGACATTCTCACCAAACACCTTGTAGAACTCTCTATACTGGCCAGAACTTTCAAGAACACTCAG'],
            [108196785,
             108196952,
             'CTCCCTGAAAGGGCAATATTTCAAATTAAACAGTACAATTCAGTTAGCTGTGGAGTCTCTGAGTGGCAGCTGGAAGAAGCACAAGTATTCTGGGCAAAAAAGGAGCAGAGTCTTGCCCTGAGTATTCTCAAGCAAATGATCAAGAAGTTGGATGCCAGCTGTGCAGCG'],
            [108198372,
             108198485,
             'AACAATCCCAGCCTAAAACTTACATACACAGAATGTCTGAGGGTTTGTGGCAACTGGTTAGCAGAAACGTGCTTAGAAAATCCTGCGGTCATCATGCAGACCTATCTAGAAAAG'],
            [108199748,
             108199965,
             'GCAGTAGAAGTTGCTGGAAATTATGATGGAGAAAGTAGTGATGAGCTAAGAAATGGAAAAATGAAGGCATTTCTCTCATTAGCCCGGTTTTCAGATACTCAATACCAAAGAATTGAAAACTACATGAAATCATCGGAATTTGAAAACAAGCAAGCTCTCCTGAAAAGAGCCAAAGAGGAAGTAGGTCTCCTTAGGGAACATAAAATTCAGACAAACAG'],
            [108200941,
             108201148,
             'ATACACAGTAAAGGTTCAGCGAGAGCTGGAGTTGGATGAATTAGCCCTGCGTGCACTGAAAGAGGATCGTAAACGCTTCTTATGTAAAGCAGTTGAAAATTATATCAACTGCTTATTAAGTGGAGAAGAACATGATATGTGGGTATTCCGACTTTGTTCCCTCTGGCTTGAAAATTCTGGAGTTTCTGAAGTCAATGGCATGATGAAG'],
            [108202171,
             108202284,
             'AGAGACGGAATGAAGATTCCAACATATAAATTTTTGCCTCTTATGTACCAATTGGCTGCTAGAATGGGGACCAAGATGATGGGAGGCCTAGGATTTCATGAAGTCCTCAATAAT'],
            [108202606,
             108202764,
             'CTAATCTCTAGAATTTCAATGGATCACCCCCATCACACTTTGTTTATTATACTGGCCTTAGCAAATGCAAACAGAGATGAATTTCTGACTAAACCAGAGGTAGCCAGAAGAAGCAGAATAACTAAAAATGTGCCTAAACAAAGCTCTCAGCTTGATGAG'],
            [108203489,
             108203627,
             'GATCGAACAGAGGCTGCAAATAGAATAATATGTACTATCAGAAGTAGGAGACCTCAGATGGTCAGAAGTGTTGAGGCACTTTGTGATGCTTATATTATATTAGCAAACTTAGATGCCACTCAGTGGAAGACTCAGAGAA'],
            [108204613,
             108204695,
             'AAGGCATAAATATTCCAGCAGACCAGCCAATTACTAAACTTAAGAATTTAGAAGATGTTGTTGTCCCTACTATGGAAATTAAG'],
            [108205696,
             108205836,
             'GTGGACCACACAGGAGAATATGGAAATCTGGTGACTATACAGTCATTTAAAGCAGAATTTCGCTTAGCAGGAGGTGTAAATTTACCAAAAATAATAGATTGTGTAGGTTCCGATGGCAAGGAGAGGAGACAGCTTGTTAAG'],
            [108206572,
             108206688,
             'GGCCGTGATGACCTGAGACAAGATGCTGTCATGCAACAGGTCTTCCAGATGTGTAATACATTACTGCAGAGAAACACGGAAACTAGGAAGAGGAAATTAACTATCTGTACTTATAAG'],
            [108213949,
             108214098,
             'GTGGTTCCCCTCTCTCAGCGAAGTGGTGTTCTTGAATGGTGCACAGGAACTGTCCCCATTGGTGAATTTCTTGTTAACAATGAAGATGGTGCTCATAAAAGATACAGGCCAAATGATTTCAGTGCCTTTCAGTGCCAAAAGAAAATGATG'],
            [108216470,
             108216635,
             'GAGGTGCAAAAAAAGTCTTTTGAAGAGAAATATGAAGTCTTCATGGATGTTTGCCAAAATTTTCAACCAGTTTTCCGTTACTTCTGCATGGAAAAATTCTTGGATCCAGCTATTTGGTTTGAGAAGCGATTGGCTTATACGCGCAGTGTAGCTACTTCTTCTATTG'],
            [108218006,
             108218092,
             'TTGGTTACATACTTGGACTTGGTGATAGACATGTACAGAATATCTTGATAAATGAGCAGTCAGCAGAACTTGTACATATAGATCTAG'],
            [108224493,
             108224607,
             'GTGTTGCTTTTGAACAGGGCAAAATCCTTCCTACTCCTGAGACAGTTCCTTTTAGACTCACCAGAGATATTGTGGATGGCATGGGCATTACGGGTGTTGAAGGTGTCTTCAGAAG'],
            [108225538,
             108225601,
             'ATGCTGTGAGAAAACCATGGAAGTGATGAGAAACTCTCAGGAAACTCTGTTAACCATTGTAGAG'],
            [108235809,
             108235945,
             'GTCCTTCTATATGATCCACTCTTTGACTGGACCATGAATCCTTTGAAAGCTTTGTATTTACAGCAGAGGCCGGAAGATGAAACTGAGCTTCACCCTACTCTGAATGCAGATGACCAAGAATGCAAACGAAATCTCAG'],
            [108236052,
             108236235,
             'TGATATTGACCAGAGTTTCAACAAAGTAGCTGAACGTGTCTTAATGAGACTACAAGAGAAACTGAAAGGAGTGGAAGAAGGCACTGTGCTCAGTGTTGGTGGACAAGTGAATTTGCTCATACAGCAGGCCATAGACCCCAAAAATCTCAGCCGACTTTTCCCAGGATGGAAAGCTTGGGTGTGA']],
        'chr13': [
            [32890598,
             32890664,
             'ATGCCTATTGGATCCAAAGAGAGGCCAACATTTTTTGAAATTTTTAAGACACGCTGCAACAAAGCAG'],
            [32893214,
             32893462,
             'ATTTAGGACCAATAAGTCTTAATTGGTTTGAAGAACTTTCTTCAGAAGCTCCACCCTATAATTCTGAACCTGCAGAAGAATCTGAACATAAAAACAACAATTACGAACCAAACCTATTTAAAACTCCACAAAGGAAACCATCTTATAATCAGCTGGCTTCAACTCCAATAATATTCAAAGAGCAAGGGCTGACTCTGCCGCTGTACCAATCTCCTGTAAAAGAATTAGATAAATTCAAATTAGACTTAG'],
            [32899213,
             32899321,
             'GAAGGAATGTTCCCAATAGTAGACATAAAAGTCTTCGCACAGTGAAAACTAAAATGGATCAAGCAGATGATGTTTCCTGTCCACTTCTAAATTCTTGTCTTAGTGAAAG'],
            [32900238,
             32900287,
             'TCCTGTTGTTCTACAATGTACACATGTAACACCACAAAGAGATAAGTCAG'],
            [32900379, 32900419, 'TGGTATGTGGGAGTTTGTTTCATACACCAAAGTTTGTGAAG'],
            [32900636,
             32900750,
             'GGTCGTCAGACACCAAAACATATTTCTGAAAGTCTAGGAGCTGAGGTGGATCCTGATATGTCTTGGTCAAGTTCTTTAGCTACACCACCCACCCTTAGTTCTACTGTGCTCATAG'],
            [32903580,
             32903629,
             'TCAGAAATGAAGAAGCATCTGAAACTGTATTTCCTCATGATACTACTGCT'],
            [32905056,
             32905167,
             'AATGTGAAAAGCTATTTTTCCAATCATGATGAAAGTCTGAAGAAAAATGATAGATTTATCGCTTCTGTGACAGACAGTGAAAACACAAATCAAAGAGAAGCTGCAAGTCATG'],
            [32906409,
             32907524,
             'GATTTGGAAAAACATCAGGGAATTCATTTAAAGTAAATAGCTGCAAAGACCACATTGGAAAGTCAATGCCAAATGTCCTAGAAGATGAAGTATATGAAACAGTTGTAGATACCTCTGAAGAAGATAGTTTTTCATTATGTTTTTCTAAATGTAGAACAAAAAATCTACAAAAAGTAAGAACTAGCAAGACTAGGAAAAAAATTTTCCATGAAGCAAACGCTGATGAATGTGAAAAATCTAAAAACCAAGTGAAAGAAAAATACTCATTTGTATCTGAAGTGGAACCAAATGATACTGATCCATTAGATTCAAATGTAGCAAATCAGAAGCCCTTTGAGAGTGGAAGTGACAAAATCTCCAAGGAAGTTGTACCGTCTTTGGCCTGTGAATGGTCTCAACTAACCCTTTCAGGTCTAAATGGAGCCCAGATGGAGAAAATACCCCTATTGCATATTTCTTCATGTGACCAAAATATTTCAGAAAAAGACCTATTAGACACAGAGAACAAAAGAAAGAAAGATTTTCTTACTTCAGAGAATTCTTTGCCACGTATTTCTAGCCTACCAAAATCAGAGAAGCCATTAAATGAGGAAACAGTGGTAAATAAGAGAGATGAAGAGCAGCATCTTGAATCTCATACAGACTGCATTCTTGCAGTAAAGCAGGCAATATCTGGAACTTCTCCAGTGGCTTCTTCATTTCAGGGTATCAAAAAGTCTATATTCAGAATAAGAGAATCACCTAAAGAGACTTTCAATGCAAGTTTTTCAGGTCATATGACTGATCCAAACTTTAAAAAAGAAACTGAAGCCTCTGAAAGTGGACTGGAAATACATACTGTTTGCTCACAGAAGGAGGACTCCTTATGTCCAAATTTAATTGATAATGGAAGCTGGCCAGCCACCACCACACAGAATTCTGTAGCTTTGAAGAATGCAGGTTTAATATCCACTTTGAAAAAGAAAACAAATAAGTTTATTTATGCTATACATGATGAAACATCTTATAAAGGAAAAAAAATACCGAAAGACCAAAAATCAGAACTAATTAACTGTTCAGCCCAGTTTGAAGCAAATGCTTTTGAAGCACCACTTACATTTGCAAATGCTGATTCAG'],
            [32910402,
             32915333,
             'GTTTATTGCATTCTTCTGTGAAAAGAAGCTGTTCACAGAATGATTCTGAAGAACCAACTTTGTCCTTAACTAGCTCTTTTGGGACAATTCTGAGGAAATGTTCTAGAAATGAAACATGTTCTAATAATACAGTAATCTCTCAGGATCTTGATTATAAAGAAGCAAAATGTAATAAGGAAAAACTACAGTTATTTATTACCCCAGAAGCTGATTCTCTGTCATGCCTGCAGGAAGGACAGTGTGAAAATGATCCAAAAAGCAAAAAAGTTTCAGATATAAAAGAAGAGGTCTTGGCTGCAGCATGTCACCCAGTACAACATTCAAAAGTGGAATACAGTGATACTGACTTTCAATCCCAGAAAAGTCTTTTATATGATCATGAAAATGCCAGCACTCTTATTTTAACTCCTACTTCCAAGGATGTTCTGTCAAACCTAGTCATGATTTCTAGAGGCAAAGAATCATACAAAATGTCAGACAAGCTCAAAGGTAACAATTATGAATCTGATGTTGAATTAACCAAAAATATTCCCATGGAAAAGAATCAAGATGTATGTGCTTTAAATGAAAATTATAAAAACGTTGAGCTGTTGCCACCTGAAAAATACATGAGAGTAGCATCACCTTCAAGAAAGGTACAATTCAACCAAAACACAAATCTAAGAGTAATCCAAAAAAATCAAGAAGAAACTACTTCAATTTCAAAAATAACTGTCAATCCAGACTCTGAAGAACTTTTCTCAGACAATGAGAATAATTTTGTCTTCCAAGTAGCTAATGAAAGGAATAATCTTGCTTTAGGAAATACTAAGGAACTTCATGAAACAGACTTGACTTGTGTAAACGAACCCATTTTCAAGAACTCTACCATGGTTTTATATGGAGACACAGGTGATAAACAAGCAACCCAAGTGTCAATTAAAAAAGATTTGGTTTATGTTCTTGCAGAGGAGAACAAAAATAGTGTAAAGCAGCATATAAAAATGACTCTAGGTCAAGATTTAAAATCGGACATCTCCTTGAATATAGATAAAATACCAGAAAAAAATAATGATTACATGAACAAATGGGCAGGACTCTTAGGTCCAATTTCAAATCACAGTTTTGGAGGTAGCTTCAGAACAGCTTCAAATAAGGAAATCAAGCTCTCTGAACATAACATTAAGAAGAGCAAAATGTTCTTCAAAGATATTGAAGAACAATATCCTACTAGTTTAGCTTGTGTTGAAATTGTAAATACCTTGGCATTAGATAATCAAAAGAAACTGAGCAAGCCTCAGTCAATTAATACTGTATCTGCACATTTACAGAGTAGTGTAGTTGTTTCTGATTGTAAAAATAGTCATATAACCCCTCAGATGTTATTTTCCAAGCAGGATTTTAATTCAAACCATAATTTAACACCTAGCCAAAAGGCAGAAATTACAGAACTTTCTACTATATTAGAAGAATCAGGAAGTCAGTTTGAATTTACTCAGTTTAGAAAACCAAGCTACATATTGCAGAAGAGTACATTTGAAGTGCCTGAAAACCAGATGACTATCTTAAAGACCACTTCTGAGGAATGCAGAGATGCTGATCTTCATGTCATAATGAATGCCCCATCGATTGGTCAGGTAGACAGCAGCAAGCAATTTGAAGGTACAGTTGAAATTAAACGGAAGTTTGCTGGCCTGTTGAAAAATGACTGTAACAAAAGTGCTTCTGGTTATTTAACAGATGAAAATGAAGTGGGGTTTAGGGGCTTTTATTCTGCTCATGGCACAAAACTGAATGTTTCTACTGAAGCTCTGCAAAAAGCTGTGAAACTGTTTAGTGATATTGAGAATATTAGTGAGGAAACTTCTGCAGAGGTACATCCAATAAGTTTATCTTCAAGTAAATGTCATGATTCTGTTGTTTCAATGTTTAAGATAGAAAATCATAATGATAAAACTGTAAGTGAAAAAAATAATAAATGCCAACTGATATTACAAAATAATATTGAAATGACTACTGGCACTTTTGTTGAAGAAATTACTGAAAATTACAAGAGAAATACTGAAAATGAAGATAACAAATATACTGCTGCCAGTAGAAATTCTCATAACTTAGAATTTGATGGCAGTGATTCAAGTAAAAATGATACTGTTTGTATTCATAAAGATGAAACGGACTTGCTATTTACTGATCAGCACAACATATGTCTTAAATTATCTGGCCAGTTTATGAAGGAGGGAAACACTCAGATTAAAGAAGATTTGTCAGATTTAACTTTTTTGGAAGTTGCGAAAGCTCAAGAAGCATGTCATGGTAATACTTCAAATAAAGAACAGTTAACTGCTACTAAAACGGAGCAAAATATAAAAGATTTTGAGACTTCTGATACATTTTTTCAGACTGCAAGTGGGAAAAATATTAGTGTCGCCAAAGAGTCATTTAATAAAATTGTAAATTTCTTTGATCAGAAACCAGAAGAATTGCATAACTTTTCCTTAAATTCTGAATTACATTCTGACATAAGAAAGAACAAAATGGACATTCTAAGTTATGAGGAAACAGACATAGTTAAACACAAAATACTGAAAGAAAGTGTCCCAGTTGGTACTGGAAATCAACTAGTGACCTTCCAGGGACAACCCGAACGTGATGAAAAGATCAAAGAACCTACTCTATTGGGTTTTCATACAGCTAGCGGGAAAAAAGTTAAAATTGCAAAGGAATCTTTGGACAAAGTGAAAAACCTTTTTGATGAAAAAGAGCAAGGTACTAGTGAAATCACCAGTTTTAGCCATCAATGGGCAAAGACCCTAAAGTACAGAGAGGCCTGTAAAGACCTTGAATTAGCATGTGAGACCATTGAGATCACAGCTGCCCCAAAGTGTAAAGAAATGCAGAATTCTCTCAATAATGATAAAAACCTTGTTTCTATTGAGACTGTGGTGCCACCTAAGCTCTTAAGTGATAATTTATGTAGACAAACTGAAAATCTCAAAACATCAAAAAGTATCTTTTTGAAAGTTAAAGTACATGAAAATGTAGAAAAAGAAACAGCAAAAAGTCCTGCAACTTGTTACACAAATCAGTCCCCTTATTCAGTCATTGAAAATTCAGCCTTAGCTTTTTACACAAGTTGTAGTAGAAAAACTTCTGTGAGTCAGACTTCATTACTTGAAGCAAAAAAATGGCTTAGAGAAGGAATATTTGATGGTCAACCAGAAAGAATAAATACTGCAGATTATGTAGGAAATTATTTGTATGAAAATAATTCAAACAGTACTATAGCTGAAAATGACAAAAATCATCTCTCCGAAAAACAAGATACTTATTTAAGTAACAGTAGCATGTCTAACAGCTATTCCTACCATTCTGATGAGGTATATAATGATTCAGGATATCTCTCAAAAAATAAACTTGATTCTGGTATTGAGCCAGTATTGAAGAATGTTGAAGATCAAAAAAACACTAGTTTTTCCAAAGTAATATCCAATGTAAAAGATGCAAATGCATACCCACAAACTGTAAATGAAGATATTTGCGTTGAGGAACTTGTGACTAGCTCTTCACCCTGCAAAAATAAAAATGCAGCCATTAAATTGTCCATATCTAATAGTAATAATTTTGAGGTAGGGCCACCTGCATTTAGGATAGCCAGTGGTAAAATCGTTTGTGTTTCACATGAAACAATTAAAAAAGTGAAAGACATATTTACAGACAGTTTCAGTAAAGTAATTAAGGAAAACAACGAGAATAAATCAAAAATTTGCCAAACGAAAATTATGGCAGGTTGTTACGAGGCATTGGATGATTCAGAGGATATTCTTCATAACTCTCTAGATAATGATGAATGTAGCACGCATTCACATAAGGTTTTTGCTGACATTCAGAGTGAAGAAATTTTACAACATAACCAAAATATGTCTGGATTGGAGAAAGTTTCTAAAATATCACCTTGTGATGTTAGTTTGGAAACTTCAGATATATGTAAATGTAGTATAGGGAAGCTTCATAAGTCAGTCTCATCTGCAAATACTTGTGGGATTTTTAGCACAGCAAGTGGAAAATCTGTCCAGGTATCAGATGCTTCATTACAAAACGCAAGACAAGTGTTTTCTGAAATAGAAGATAGTACCAAGCAAGTCTTTTCCAAAGTATTGTTTAAAAGTAACGAACATTCAGACCAGCTCACAAGAGAAGAAAATACTGCTATACGTACTCCAGAACATTTAATATCCCAAAAAGGCTTTTCATATAATGTGGTAAATTCATCTGCTTTCTCTGGATTTAGTACAGCAAGTGGAAAGCAAGTTTCCATTTTAGAAAGTTCCTTACACAAAGTTAAGGGAGTGTTAGAGGAATTTGATTTAATCAGAACTGAGCATAGTCTTCACTATTCACCTACGTCTAGACAAAATGTATCAAAAATACTTCCTCGTGTTGATAAGAGAAACCCAGAGCACTGTGTAAACTCAGAAATGGAAAAAACCTGCAGTAAAGAATTTAAATTATCAAATAACTTAAATGTTGAAGGTGGTTCTTCAGAAAATAATCACTCTATTAAAGTTTCTCCATATCTCTCTCAATTTCAACAAGACAAACAACAGTTGGTATTAGGAACCAAAGTGTCACTTGTTGAGAACATTCATGTTTTGGGAAAAGAACAGGCTTCACCTAAAAACGTAAAAATGGAAATTGGTAAAACTGAAACTTTTTCTGATGTTCCTGTGAAAACAAATATAGAAGTTTGTTCTACTTACTCCAAAGATTCAGAAAACTACTTTGAAACAGAAGCAGTAGAAATTGCTAAAGCTTTTATGGAAGATGATGAACTGACAGATTCTAAACTGCCAAGTCATGCCACACATTCTCTTTTTACATGTCCCGAAAATGAGGAAATGGTTTTGTCAAATTCAAGAATTGGAAAAAGAAGAGGAGAGCCCCTTATCTTAGTGG'],
            [32918695,
             32918790,
             'GAGAACCCTCAATCAAAAGAAACTTATTAAATGAATTTGACAGGATAATAGAAAATCAAGAAAAATCCTTAAAGGCTTCAAAAAGCACTCCAGATG'],
            [32920964,
             32921033,
             'GCACAATAAAAGATCGAAGATTGTTTATGCATCATGTTTCTTTAGAGCCGATTACCTGTGTACCCTTTCG'],
            [32928998,
             32929425,
             'CACAACTAAGGAACGTCAAGAGATACAGAATCCAAATTTTACCGCACCTGGTCAAGAATTTCTGTCTAAATCTCATTTGTATGAACATCTGACTTTGGAAAAATCTTCAAGCAATTTAGCAGTTTCAGGACATCCATTTTATCAAGTTTCTGCTACAAGAAATGAAAAAATGAGACACTTGATTACTACAGGCAGACCAACCAAAGTCTTTGTTCCACCTTTTAAAACTAAATCACATTTTCACAGAGTTGAACAGTGTGTTAGGAATATTAACTTGGAGGAAAACAGACAAAAGCAAAACATTGATGGACATGGCTCTGATGATAGTAAAAATAAGATTAATGACAATGAGATTCATCAGTTTAACAAAAACAACTCCAATCAAGCAGTAGCTGTAACTTTCACAAAGTGTGAAGAAGAACCTTTAG'],
            [32930565,
             32930746,
             'ATTTAATTACAAGTCTTCAGAATGCCAGAGATATACAGGATATGCGAATTAAGAAGAAACAAAGGCAACGCGTCTTTCCACAGCCAGGCAGTCTGTATCTTGCAAAAACATCCACTCTGCCTCGAATCTCTCTGAAAGCAGCAGTAGGAGGCCAAGTTCCCTCTGCGTGTTCTCATAAACAG'],
            [32931879,
             32932066,
             'CTGTATACGTATGGCGTTTCTAAACATTGCATAAAAATTAACAGCAAAAATGCAGAGTCTTTTCAGTTTCACACTGAAGATTATTTTGGTAAGGAAAGTTTATGGACTGGAAAAGGAATACAGTTGGCTGATGGTGGATGGCTCATACCCTCCAATGATGGAAAGGCTGGAAAAGAAGAATTTTATAG'],
            [32936660,
             32936830,
             'GGCTCTGTGTGACACTCCAGGTGTGGATCCAAAGCTTATTTCTAGAATTTGGGTTTATAATCACTATAGATGGATCATATGGAAACTGGCAGCTATGGAATGTGCCTTTCCTAAGGAATTTGCTAATAGATGCCTAAGCCCAGAAAGGGTGCTTCTTCAACTAAAATACAG'],
            [32937316,
             32937670,
             'ATATGATACGGAAATTGATAGAAGCAGAAGATCGGCTATAAAAAAGATAATGGAAAGGGATGACACAGCTGCAAAAACACTTGTTCTCTGTGTTTCTGACATAATTTCATTGAGCGCAAATATATCTGAAACTTCTAGCAATAAAACTAGTAGTGCAGATACCCAAAAAGTGGCCATTATTGAACTTACAGATGGGTGGTATGCTGTTAAGGCCCAGTTAGATCCTCCCCTCTTAGCTGTCTTAAAGAATGGCAGACTGACAGTTGGTCAGAAGATTATTCTTCATGGAGCAGAACTGGTGGGCTCTCCTGATGCCTGTACACCTCTTGAAGCCCCAGAATCTCTTATGTTAAAG'],
            [32944539,
             32944694,
             'ATTTCTGCTAACAGTACTCGGCCTGCTCGCTGGTATACCAAACTTGGATTCTTTCCTGACCCTAGACCTTTTCCTCTGCCCTTATCATCGCTTTTCAGTGATGGAGGAAATGTTGGTTGTGTTGATGTAATTATTCAAAGAGCATACCCTATACAG'],
            [32945093,
             32945237,
             'TGGATGGAGAAGACATCATCTGGATTATACATATTTCGCAATGAAAGAGAGGAAGAAAAGGAAGCAGCAAAATATGTGGAGGCCCAACAAAAGAGACTAGAAGCCTTATTCACTAAAATTCAGGAGGAATTTGAAGAACATGAAG'],
            [32950807,
             32950928,
             'AAAACACAACAAAACCATATTTACCATCACGTGCACTAACAAGACAGCAAGTTCGTGCTTTGCAAGATGGTGCAGAGCTTTATGAAGCAGTGAAGAATGCAGCAGACCCAGCTTACCTTGAG'],
            [32953454,
             32953652,
             'GGTTATTTCAGTGAAGAGCAGTTAAGAGCCTTGAATAATCACAGGCAAATGTTGAATGATAAGAAACAAGCTCAGATCCAGTTGGAAATTAGGAAGGCCATGGAATCTGCTGAACAAAAGGAACAAGGTTTATCAAGGGATGTCACAACCGTGTGGAAGTTGCGTATTGTAAGCTATTCAAAAAAAGAAAAAGATTCAG'],
            [32953887,
             32954050,
             'TTATACTGAGTATTTGGCGTCCATCATCAGATTTATATTCTCTGTTAACAGAAGGAAAGAGATACAGAATTTATCATCTTGCAACTTCAAAATCTAAAAGTAAATCTGAAAGAGCTAACATACAGTTAGCAGCGACAAAAAAAACTCAGTATCAACAACTACCG'],
            [32954144,
             32954282,
             'GTTTCAGATGAAATTTTATTTCAGATTTACCAGCCACGGGAGCCCCTTCACTTCAGCAAATTTTTAGATCCAGACTTTCAGCCATCTTGTTCTGAGGTGGACCTAATAGGATTTGTCGTTTCTGTTGTGAAAAAAACAG'],
            [32968826,
             32969070,
             'GACTTGCCCCTTTCGTCTATTTGTCAGACGAATGTTACAATTTACTGGCAATAAAGTTTTGGATAGACCTTAATGAGGACATTATTAAGCCTCATATGTTAATTGCTGCAAGCAACCTCCAGTGGCGACCAGAATCCAAATCAGGCCTTCTTACTTTATTTGCTGGAGATTTTTCTGTGTTTTCTGCTAGTCCAAAAGAGGGCCACTTTCAAGAGACATTCAACAAAATGAAAAATACTGTTGAG'],
            [32971035,
             32971181,
             'AATATTGACATACTTTGCAATGAAGCAGAAAACAAGCTTATGCATATACTGCATGCAAATGATCCCAAGTGGTCCACCCCAACTAAAGACTGTACTTCAGGGCCGTACACTGCTCAAATCATTCCTGGTACAGGAAACAAGCTTCTG'],
            [32972299,
             32972907,
             'ATGTCTTCTCCTAATTGTGAGATATATTATCAAAGTCCTTTATCACTTTGTATGGCCAAAAGGAAGTCTGTTTCCACACCTGTCTCAGCCCAGATGACTTCAAAGTCTTGTAAAGGGGAGAAAGAGATTGATGACCAAAAGAACTGCAAAAAGAGAAGAGCCTTGGATTTCTTGAGTAGACTGCCTTTACCTCCACCTGTTAGTCCCATTTGTACATTTGTTTCTCCGGCTGCACAGAAGGCATTTCAGCCACCAAGGAGTTGTGGCACCAAATACGAAACACCCATAAAGAAAAAAGAACTGAATTCTCCTCAGATGACTCCATTTAAAAAATTCAATGAAATTTCTCTTTTGGAAAGTAATTCAATAGCTGACGAAGAACTTGCATTGATAAATACCCAAGCTCTTTTGTCTGGTTCAACAGGAGAAAAACAATTTATATCTGTCAGTGAATCCACTAGGACTGCTCCCACCAGTTCAGAAGATTATCTCAGACTGAAACGACGTTGTACTACATCTCTGATCAAAGAACAGGAGAGTTCCCAGGCCAGTACGGAAGAATGTGAGAAAAATAAGCAGGACACAATTACAACTAAAAAATATATCTAA']],
        'chr17': [
            [41276034,
             41276113,
             'CAGATGGGACACTCTAAGATTTTCTGCATAGCATTAATGACATTTTGTACTTCTTCAACGCGAAGAGCAGATAAATCCAT'],
            [41267743,
             41267796,
             'TTGCAAAATATGTGGTCACACTTTGTGGAGACAGGTTCCTTGATCAACTCCAGA'],
            [41258473,
             41258550,
             'CTTTTGGTTATATCATTCTTACATAAAGGACACTGTGAAGGCCCTTTCTTCTGGTTGAGAAGTTTCAGCATGCAAAAT'],
            [41256885,
             41256973,
             'ACTCCAAACCTGTGTCAAGCTGAAAAGCACAAATGATTTTCAATAGCTCTTCAACAAGTTGACTAAATCTCGTACTTTCTTGTAGGCTC'],
            [41256139,
             41256278,
             'CAAGGAAGGATTTTCGGGTTCACTCTGTAGAAGTCTTTTGGCACGGTTTCTGTAGCCCATACTTTGGATGATAGAAACTTCATCTTTTAGATGTTCAGGAGAGTTATTTTCCTTTTTTGCAAAATTATAGCTGTTTGCAT'],
            [41251792,
             41251897,
             'CCAATTCAATGTAGACAGACGTCTTTTGAGGTTGTATCCGCTGCTTTGTCCTCAGAGTTCTCACAGTTCCAAGGTTAGAGAGTTGGACACTGAGACTGGTTTCCTG'],
            [41249261,
             41249306,
             'CTGCAATAAGTTGCCTTATTAACGGTATCTTCAGAAGAATCAGATC'],
            [41247863,
             41247939,
             'CCTTTTTTGCAGAATCCAAACTGATTTCATCCCTGGTTCCTTGAGGGGTGATTTGTAACAATTCTTGATCTCCCACA'],
            [41243452,
             41246877,
             'CTAAGTTTGAATCCATGCTTTGCTCTTCTTGATTATTTTCTTCCAAGCCCGTTCCTCTTTCTTCATCATCTGAAACCAATTCCTTGTCACTCAGACCAACTCCCTGGCTTTCAGACTGATGCCTCATTTGTTTGGAAGAACCAATCAAGAAAGGATCCTGGGTGTTTGTATTTGCAGTCAAGTCTTCCAATTCACTGCACTGTGAAGAAAACAAGCTAGCAGAACATTTTGTTTCCTCACTAAGGTGATGTTCCTGAGATGCCTTTGCCAATATTACCTGGTTACTGCAGTCATTTAAGCTATTCTTCAATGATAATAAATTCTCCTCTGTGTTCTTAGACAGACACTCGGTAGCAACGGTGCTATGCCTAGTAGACTGAGAAGGTATATTGTTTACTTTACCAAATAACAAGTGTTGGAAGCAGGGAAGCTCTTCATCCTCACTAGATAAGTTCTCTTCTGAGGACTCTAATTTCTTGGCCCCTCTTCGGTAACCCTGAGCCAAATGTGTATGGGTGAAAGGGCTAGGACTCCTGCTAAGCTCTCCTTTCTGGACGCTTTTGCTAAAAACAGCAGAACTTTCCTTAATGTCATTTTCAGCAAAACTAGTATCTTCCTTTATTTCACCATCATCTAACAGGTCATCAGGTGTCTCAGAACAAACCTGAGATGCATGACTACTTCCCATAGGCTGTTCTAAGTTATCTGAAATCAGATATGGAGAGAAATCTGTATTAACAGTCTGAACTACTTCTTCATATTCTTGCTTTTTTATTTCAGGATGCTTACAATTACTTCCAGGAAGACTTTGTTTATAGACCTCAGGTTGCAAAACCCCTAATCTAAGCATAGCATTCAATTTTGGCCCTCTGTTTCTACCTAGTTCTGCTTGAATGTTTTCATCACTGGAACCTATTTCATTAATACTGGAGCCCACTTCATTAGTACTGGAACCTACTTCATTAATATTGCTTGAGCTGGCTTCTTTAAAAACATTTTCTCTAATGTTATTACGGCTAATTGTGCTCACTGTACTTGGAATGTTCTCATTTCCCATTTCTCTTTCAGGTGACATTGAATGTTCCTCAAAGTTTTCCTCTAGCAGATTTTTCTTACATTTAGTTTTAACAAATGACTTGATGGGAAAAAGTGGTGGTATACGATATGGGTTTTGTAAAAGTCCATGTTTATTTGGAGTAATGAGTCCAGTTTCGTTGCCTCTGAACTGAGATGATAGACAAAACCTAGAGCCTCCTTTGATACTACATTTGGCATTATCAACTGGCTTATCTTTCTGACCAACCACAGGAAAGCCTGCAGTGATATTAACTGTCTGTACAGGCTTGATATTAGACTCATTCTTTCCTTGATTTTCTTCCTTTTGTTCACATTCAAAAGTGACTTTTGGACTTTGTTTCTTTAAGGACCCAGAGTGGGCAGAGAATGTTGCACATTCCTCTTCTGCATTTCCTGGATTTGAAAACGGAGCAAATGACTGGCGCTTTGAAACCTTGAATGTATTCTGCAAATACTGAGCATCAAGTTCACTTTCTTCCATTTCTATGCTTGTTTCCCGACTGTGGTTAACTTCATGTCCCAATGGATACTTAAAGCCTTCTGTGTCATTTCTATTATCTTTGGAACAACCATGAATTAGTCCCTTGGGGTTTTCAAATGCTGCACACTGACTCACACATTTATTTGGTTCTGTTTTTGCCTTCCCTAGAGTGCTAACTTCCAGTAACGAGATACTTTCCTGAGTGCCATAATCAGTACCAGGTACCAATGAAATACTGCTACTCTCTACAGATCTTTCAGTTTGCAAAACCCTTTCTCCACTTAACATGAGATCTTTGGGGTCTTCAGCATTATTAGACACTTTAACTGTTTCTAGTTTCTCTTCTTTTTCTTCTCTTGGAAGGCTAGGATTGACAAATTCTTTAAGTTCACTGGTATTTGAACACTTAGTAAAAGAACCAGGTGCATTTGTTAACTTCAGCTCTGGGAAAGTATCGCTGTCATGTCTTTTACTTGTCTGTTCATTTGGCTTGTTACTCTTCTTGGCTCCAGTTGCAGGTTCTTTACCTTCCATGAGTTGTAGGTTTCTGCTGTGCCTGACTGGCATTTGGTTGTACTTTTTTTTCTTTATCTCTTCACTGCTAGAACAACTATCAATTTGCAATTCAGTACAATTAGGTGGGCTTAGATTTCTACTGACTACTAGTTCAAGCGCATGAATATGCCTGGTAGAAGACTTCCTCCTCAGCCTATTCTTTTTAGGTGCTTTTGAATTGTGGATATTTAATTCGAGTTCCATATTGCTTATACTGCTGCTTATAGGTTCAGCTTTCGTTTTGAAAGCAGATTCTTTTTCGAGTGATTCTATTGGGTTAGGATTTTTCTCATTCTGAATAGAATCACCTTTTGTTTTATTCTCATGACCACTATTAGTAATATTCATCACTTGACCATTCTGCTCCGTTTGGTTAGTTCCCTGATTTATCATTTCAGGAGTCTTTTGAACTGCCAAATCTGCTTTCTTGATAAAATCCTCAGGATGAAGGCCTGATGTAGGTCTCCTTTTACGCTTTAATTTATTTGTGAGGGGACGCTCTTGTATTATCTGTGGCTCAGTAACAAATGCTCCTATAATTAGATTTTCAGTTACATGGCTTAAGTTGGGGAGGCTTGCCTTCTTCCGATAGGTTTTCCCAAATATTTTGTCTTCAATATTACTCTCTACTGATTTGGAGTGAACTCTTTCACTTTTACATATTAAAGCCTCATGAGGATCACTGGCCAGTAAGTCTATTTTCTCTGAAGAACCAGAATATTCATCTACCTCATTTAGAACGTCCAATACATCAGCTACTTTGGCATTTGATTCAGACTCCCCATCATGTGAGTCATCAGAACCTAACAGTTCATCACTTCTGGAAAACCACTCATTAACTTTCTGAATGCTGCTATTTAGTGTTATCCAAGGAACATCTTCAGTATCTCTAGGATTCTCTGAGCATGGCAGTTTCTGCTTATTCCATTCTTTTCTCTCACACAGGGGATCAGCATTCAGATCTACCTTTTTTTCTGTGCTGGGAGTCCGCCTATCATTACATGTTTCCTTACTTCCAGCCCATCTGTTATGTTGGCTCCTTGCTAAGCCAGGCTGTTTGCTTTTATTACAGAATTCAGCCTTTTCTACATTCATTCTGTCTTTAGTGAGTAATAAACTGCTGTTCTCATGCTGTAATGAGCTGGCATGAGTATTTGTGCCACATGGCTCCACATGCAAGTTTGAAACAGAACTACCCTGATACTTTTCTGGATGCCTCTCAGCTGCACGCTTCTCAGTGGTGTTCAAATCATTATTACTGGGTTGATGATGTTCAGTATTTGTTACATCCGTCTCAGAAAATTCACAAGCAG'],
            [41242961,
             41243049,
             'CTGAGTGGTTAAAATGTCACTCTGAGAGGATAGCCCTGAGCAGTCTTCAGAGACGCTTGTTTCACTCTCACACCCAGATGCTGCTTCAC'],
            [41234421,
             41234592,
             'CTTTTTCTGATGTGCTTTGTTCTGGATTTCGCAGGTCCTCAAGGGCAGAAGAGTCACTTATGATGGAAGGGTAGCTGTTAGAAGGCTGGCTCCCATGCTGTTCTAACACAGCTTCTAGTTCAGCCATTTCCTGCTGGAGCTTTATCAGGTTATGTTGCATGGTATCCCTCTG'],
            [41228505,
             41228631,
             'CTTTCCACTCCTGGTTCTTTATTTTTACTGGTAGAACTATCTGCAGACACCTCAAACTTGTCAGCAGAAAGGCCTTCTGGATTCTGGCTTATAGGGTATTCACTACTTTTCTGTGAAGTTAATACTG'],
            [41226348,
             41226538,
             'CTAGATCTTGCCTTGGCAAGTAAGATGTTTCCGTCAAATCGTGTGGCCCAGACTCTTCCAGCTGTTGCTCCTCCACATCAACAACCTTAATGAGCTCCTCTTGAGATGGGTAGTTTCTATTCTGAAGACTCCCAGAGCAACTGTGCATGTACCACCTATCATCTAATGATGGGCATTTAGAAGGGGATGAC'],
            [41222945,
             41223255,
             'AAATTCTTCTGGGGTCAGGCCAGACACCACCATGGACATTCTTTTGTTGACCCTTTCTGTTGAAGCTGTCAATTCTGGCTTCTCCCTGCTCACACTTTCTTCCATTGCATTATACCCAGCAGTATCAGTAGTATGAGCAGCAGCTGGACTCTGGGCAGATTCTGCAACTTTCAATTGGGGAACTTTCAATGCAGAGGTTGAAGATGGTATGTTGCCAACACGAGCTGACTCTGGGGCTCTGTCTTCAGAAGGATCAGATTCAGGGTCATCAGAGAAGAGGCTGATTCCAGATTCCAGGTAAGGGGTTCCCT'],
            [41219625,
             41219712,
             'CTGTTTTCATAACAACATGAGTAGTCTCTTCAGTAATTAGATTAGTTAAAGTGATGTGGTGTTTTCTGGCAAACTTGTACACGAGCAT'],
            [41215891,
             41215968,
             'AGAAATAGCTAACTACCCATTTTCCTCCCGCAATTCCTAGAAAATATTTCAGTGTCCGTTCACACACAAACTCAGCAT'],
            [41215350, 41215390, 'CTCATTCAGCATTTTTCTTTCTTTAATAGACTGGGTCACCC'],
            [41209069,
             41209152,
             'CTTTCTGTCCTGGGATTCTCTTGCTCGCTTTGGACCTTGGTGGTTTCTTCCATTGACCACATCTCCTCTGACTTCAAAATCATG'],
            [41203080,
             41203134,
             'CTGTGGGCATGTTGGTGAAGGGCCCATAGCAACAGATTTCTAGCCCCCTGAAGAT'],
            [41201138,
             41201211,
             'TGTGCCAAGGGTGAATGATGAAAGCTCCTTCACCACAGAAGCACCACACAGCTGTACCATCCATTCCAGTTGAT'],
            [41199660,
             41199720,
             'CATGGAAGCCATTGTCCTCTGTCCAGGCATCTGGCTGCACAACCACAATTGGGTGGACACC'],
            [41197695,
             41197819,
             'TCAGTAGTGGCTGTGGGGGATCTGGGGTATCAGGTAGGTGTCCAGCTCCTGGCACTGGTAGAGTGCTACACTGTCCAACACCCACTCTCGGGTCACCACAGGTGCCTCACACATCTGCCCAATTG']],
        'chr22': [
            [29130391,
             29130709,
             'CAAGATTGGCAAATCCATCCTGAAGGGCCCATAATCGAGCCCAGGGGGCAGGGGTAGGCTCCTCAGGTTCTTGGTCCTCAGGTTCTTGGTCCTCAGGAATAGAATAGAGTTCCTGAGTGGACACTGTCTCTAAGGAGCTCAGTGTCCCAGAGCTGGAGTGAGAGGACTGGCTGGAGTTTGGCATCGTGCTGGTAGAGGAGCTGGATATGCCCTGGGACTGTGAGGAGGAGCCTTGGGACTGGGTAACGCTGCCATGGGGCTGTGAACAGGCACTGCTGCCATGAGACTGCTGAGCCTCAACATCCGACTCCCGAGACAT'],
            [29121231,
             29121355,
             'CCTGAAAATCCGAAAGTGTTTCTTGCTGTATGTTCGGTATTTATCTGTTCTTTTCAGCAGTGGTTCATCAAAGCAATATTCACAGCTTTTGTCCCTCCCAAACCAGTAGTTGTCATTCACACATT'],
            [29120965,
             29121112,
             'CTTTATTTCTGCTTAGTGACAGTGCAATTTCAGAATTGTTATTCAAAGGACGGCGTTTTCCTTTCCCTACAAGCTCTGTATTTACAAAGGTTCCATTGCCACTGTGATCTTCTATGTATGCAATGTAAGAGTTTTTAGGACCCACTTC'],
            [29115383,
             29115473,
             'CTTCCAAGAGTTTTTGACATGATGTATTCATCTCTTAATGCCTTAGGATAAACTGACTGATCATCTACAGTCAGATCAAAAAAGACAAAAA'],
            [29107897,
             29108005,
             'TGCCTCTCTTGCTGAACCAATAGCAAACTTCCTTTTGCTGATGATCTTTATGGCTACTTTCTTACATGTTTTCCTCTCGAAAGCCAGCTTTACCTCTCCACAGGCACCA'],
            [29105994,
             29106047,
             'ATGATTTAGCTTTTTCAAAATTTCTATTTCTGTTTCAACATTGAGAGCTGGGTC'],
            [29099493,
             29099554,
             'AATTCCAAAACAATATAATAATCTTCTGCATCAAAAAAGTTTTTAATCTTGATGATGCAAGG'],
            [29095826,
             29095925,
             'CTGCACAGCCAAGAGCATCTGGTAAAAATAGAGCTTGCAGGTAGCTTCTTTCAGGCGTTTATTCCCCACCACTTTGTCAAACAGCTCTCCCCCTTCCATC'],
            [29092889,
             29092975,
             'CTTTATAAGACAGTCCTCTTCTTGAGATGACAGTAAAACATTCTCTGGCTTTAAGTCACGGTGTATAATACCGTTTTCATGAAGGTA'],
            [29091698,
             29091861,
             'CAGATAAAAAGAATAACTCCTAAACTCCAGCAGTCCACAGCACGGTTATACCCAGCAGTCCCAACAGAAACAAGAACTTCAGGCGCCAAGTAGGTGGGGGTTCCACATAAGGTTCTCATGAGAGAGGTCTCTCCCAAAATCTTGGAGTGCCCAAAATCAGTAAT'],
            [29091115,
             29091230,
             'CTTTCTCTGAGACTTCTGCCCAGACTTCAGGAATGAAGTTGTATTTTCCACTGGTGATCTGATCCTTCAGTGACACTTGAGTCCTATGCTCAGAGAAAGGTGGATACCCACTAAGG'],
            [29090020,
             29090105,
             'CTGAAGCCACGGGTGTCTTAAGGCTTCTTCTGTCGTAAAACGTGCCTTTGGATCCACTACCAACAACTTCTTGACAAGGTCCAGAG'],
            [29085123,
             29085203,
             'CTGGGCTAGAACCTGGGGTAGAGCTGTGGATTCATTTTCCTCAGACAGAAGATCTTGAAACTTTCTCTTCATGTCTTCATC'],
            [29083885,
             29083974,
             'TCACAACACAGCAGCACACACAGCTGGGCGCTTTGTGGTCTCGGCACCCTCGGCTTCCCCTTCACGGGGCCGCTTTCGACTAGTAGAAGG']
        ]
    }

    # first range of each chromosome is pathogenic, second range is not
    pathogenic_or_not_pathogenic = {
        'chr11': [[108093559, 108236203], [108236204, 108239826], 'ATM'],
        'chr13': [[32889611, 32972575], [32972576, 32973347], 'BRCA2'],
        'chr17': [[41197717, 41277387], [41196312, 41197716], 'BRCA1'],
        'chr22': [[29083970, 29137826], [29083751, 29083969], 'CHEK2']
    }

    stop_codons_MT = ['AGA', 'AGG']
    stop_codons = ['TAA', 'TAG', 'TGA']

    variant = input_dialog()
    # variant = 'chr11:108153470A>T'
    # variant = 'chr11:108153470A>GATTACAT'
    # variant = 'chr11:108153470000A>GATTACA'
    # variant = 'chr11:108153470A>GATTAGA'
    # variant = 'chr11:108153470AGA>A'

    variant_bases = ''.join(char for char in variant.split(':')[-1] if not char.isnumeric()).split('>')
    variant_ref = variant_bases[0]
    variant_alt = variant_bases[1]
    variant_chr = variant.split(':')[0]
    variant_pos = int(''.join(char for char in variant.split(':')[-1] if char.isnumeric()))
    variant_pos_end = variant_pos + max(len(variant_ref), len(variant_alt)) - 1
    # print('The variant', variant, 'spans on', [variant_pos, variant_pos_end], 'positions of', variant_chr, '...')

    seq_chr11 = ''.join([x[2] for x in ref_dict['chr11']])
    seq_chr13 = ''.join([x[2] for x in ref_dict['chr13']])
    seq_chr17 = ''.join([reverse_complement(x[2]) for x in ref_dict['chr17']])
    seq_chr22 = ''.join([reverse_complement(x[2]) for x in ref_dict['chr22']])

    # seq_chr11_split = [seq_chr11[_:_ + 3] for _ in range(0, len(seq_chr11), 3)]
    # seq_chr11_stop = any([x for x in stop_codons if x in seq_chr11_split[-5:]])
    #
    # seq_chr13_split = [seq_chr13[_:_ + 3] for _ in range(0, len(seq_chr13), 3)]
    # seq_chr13_stop = any([x for x in stop_codons if x in seq_chr13_split[-5:]])
    #
    # seq_chr17_split = [seq_chr17[_:_ + 3] for _ in range(0, len(seq_chr17), 3)]
    # seq_chr17_stop = any([x for x in stop_codons if x in seq_chr17_split[-5:]])
    #
    # seq_chr22_split = [seq_chr22[_:_ + 3] for _ in range(0, len(seq_chr22), 3)]
    # seq_chr22_stop = any([x for x in stop_codons if x in seq_chr22_split[-5:]])
    #
    # print('seq_chr11_stop', seq_chr11_stop, 'seq_chr13_stop', seq_chr13_stop,
    #       'seq_chr17_stop', seq_chr17_stop, 'seq_chr22_stop', seq_chr22_stop)
    # print('seq_chr11_split[-5:]', seq_chr11_split[-5:])
    # print('seq_chr13_split[-5:]', seq_chr13_split[-5:])
    # print('seq_chr17_split[-5:]', seq_chr17_split[-5:])
    # print('seq_chr22_split[-5:]', seq_chr22_split[-5:])

    # considering start of the variant normal (not previously shifted)
    try:
        chrom_range = ref_dict[variant_chr]
        # print('chrom_range', chrom_range)
        chrom_seq = ''.join([x[2] for x in ref_dict[variant_chr]]) \
            if variant_chr == 'chr11' or variant_chr == 'chr13' \
            else ''.join([reverse_complement(x[2]) for x in ref_dict[variant_chr]])

        yay = 0
        for v in chrom_range:
            if v[0] <= variant_pos and variant_pos_end <= v[1]:
                yay += 1
                # print('Yay - variant belongs to the ABC region, and we can cut out its own little region')
                seq_ref = v[2]
                dist_to_start = int(variant_pos) - int(v[0])
                dist_to_start_full = int(variant_pos) - int(v[0])
                # print('dist_to_start', dist_to_start)
                # dist_to_start = dist_to_start - 2 if dist_to_start >= 2 else dist_to_start
                # print('dist_to_start', dist_to_start)
                seq_ref_mini = seq_ref[dist_to_start:dist_to_start + len(variant_ref) + 2]
                seq_alt_mini = variant_alt + seq_ref[
                                             dist_to_start + len(variant_ref):dist_to_start + len(variant_ref) + 2]

                seq_ref_mini_c = reverse_complement(seq_ref[dist_to_start - 2:dist_to_start + len(variant_ref)])
                seq_alt_mini_c = reverse_complement(seq_ref[dist_to_start - 2:dist_to_start] + variant_alt)

                seq_ref_bothends = seq_ref[dist_to_start - 2:dist_to_start + len(variant_ref) + 2]
                seq_ref_bothends_c = reverse_complement(seq_ref[dist_to_start - 2:dist_to_start + len(variant_ref) + 2])
                seq_alt_bothends = seq_ref[dist_to_start - 2:dist_to_start] + variant_alt + \
                                   seq_ref[dist_to_start + len(variant_ref):dist_to_start + len(variant_ref) + 2]
                seq_alt_bothends_c = reverse_complement(seq_ref[dist_to_start - 2:dist_to_start] + variant_alt +
                                                        seq_ref[dist_to_start + len(variant_ref):dist_to_start + len(
                                                            variant_ref) + 2])

                # print('Variant:', variant_ref, '>>>', variant_alt)
                # print('Variant + next 2 bases:', seq_ref_mini, '(' + seq_ref_mini_c + ')',
                #       '>>>', seq_alt_mini, '(' + seq_alt_mini_c + ')')
                # print('Prev 2 bases + variant + next 2 bases: ' +
                #       seq_ref_bothends, '(' + seq_ref_bothends_c + ')' + ' >>> ' +
                #       seq_alt_bothends, '(' + seq_alt_bothends_c + ')\n')

                seq_alt_split = [seq_alt_mini[_:_ + 3] for _ in range(0, len(seq_alt_mini), 3)]
                seq_alt_c_split = [seq_alt_mini_c[_:_ + 3] for _ in range(0, len(seq_alt_mini_c), 3)]
                # print('seq_alt_split', seq_alt_split)
                # print('seq_alt_c_split', seq_alt_c_split)

                # detecting stop codon: alt sequence + next 2 bases includes stop codon
                if 'MT' in variant_chr:
                    is_stop_codon = any([x for x in stop_codons_MT if x in seq_alt_split or x in seq_alt_c_split])
                    is_stop_codon_c = any([x for x in stop_codons_MT if x in seq_alt_c_split])
                else:
                    is_stop_codon = any([x for x in stop_codons if x in seq_alt_split or x in seq_alt_c_split])
                    is_stop_codon_c = any([x for x in stop_codons if x in seq_alt_c_split])
                # print('is_stop_codon', is_stop_codon)

                # detecting frameshift: length of the change from the insertion or deletion is not divisible by 3
                is_frameshift = True if len(variant_alt) != len(variant_ref) and \
                                        abs(len(variant_alt) - len(variant_ref)) % 3 != 0 else False
                # print('is_frameshift', is_frameshift)

                # the variant is considered pathogenic if is within designated positions
                curr_ponp = pathogenic_or_not_pathogenic[variant_chr]
                is_in_pathogenic_range = curr_ponp[0][0] <= variant_pos <= curr_ponp[0][1]
                is_in_non_pathogenic_range = curr_ponp[1][0] <= variant_pos <= curr_ponp[1][1]
                if is_in_pathogenic_range and (is_stop_codon or is_frameshift):
                    is_pathogenic = True
                elif is_in_non_pathogenic_range:
                    is_pathogenic = False
                else:
                    is_pathogenic = False
                # print('is_pathogenic', is_pathogenic)

                # print('Verdict: variant', 'is' if is_pathogenic else 'is NOT', 'pathogenic',
                #       'because it belongs to the',
                #       'pathogenic' if is_in_pathogenic_range else 'non-pathogenic',
                #       'range', curr_ponp[0], 'of', curr_ponp[2], 'gene',
                #       'while', 'being' if is_stop_codon else 'NOT being', 'a stop codon',
                #       'and', 'being' if is_frameshift else 'NOT being', 'a frameshift')
                print_is_pathogenic = str(1) if is_pathogenic else str(0)
                print_is_frameshift = str(1) if is_frameshift else str(0)
                print_is_stop_codon = str(1) if is_stop_codon else str(0)
                # print_seq = seq_ref_bothends + '>' + seq_alt_bothends + '_' + \
                #             seq_ref_bothends_c + '>' + seq_alt_bothends_c if is_stop_codon or is_frameshift else ''
                print_seq = 'f_' + seq_ref_mini + '>' + seq_alt_mini if is_frameshift else ''
                print_seq = 'f_' + seq_ref_bothends + '>' + seq_alt_bothends if is_stop_codon else print_seq
                print_seq = 'r_' + seq_ref_bothends_c + '>' + seq_alt_bothends_c if is_stop_codon_c else print_seq
                print(variant + ',' + print_is_pathogenic + ',' + print_is_frameshift + ',' + print_is_stop_codon +
                      ',' + print_seq)

                break
        if yay == 0:
            print('Oh no! Variant\'s position', str(variant_chr) + ':' + str(variant_pos),
                  'is not in the designated chromosome range! Choose wisely ...')

    except KeyError as e:
        print('Oh no! Variant\'s chromosome', e,
              'is not in the ABC region! Choose wisely ...')
